export const FIRST_ANIMATION_START_DELAY_MS = 1500;
export const FIRST_ANIMATED_TRANSITION_DURATION_MS = 4000;
export const ANIMATION_START_DELAY_MS = 750;
export const ANIMATED_TRANSITION_DURATION_MS = 3000;
export const USER_TRANSITION_DURATION_MS = 500;
